### ISSUE TITLE
GitLab CI performance

### ISSUE THREAD

**Issue by azdanov** [BuildingXwithJS/building-products-with-js#33]
Currently, I'm going through the course, which I think is amazing, and wonder if there are any ways to speed up the build/test/deploy process from CI. I feel that it's quite wasteful from the pipeline point of view to redownload the image from docker hub, instead of using the built images.

I understand that this course was made when the technologies used were quite new, and wonder if there are any better ways to approach the CI/CD nowadays.

**Comment by yamalight** [comment]
You can of course test the local image, but the point of pulling it from remote is to ensure that nothing breaks during push process (it's a very unlikely scenario, but we've had it happen more than once on private registries due to some obscure bugs).

**Comment by azdanov** [comment]
I see. Thank you for clarification.
